import { describe, expect, test } from "bun:test"
import fs from "node:fs"
import path from "node:path"

const ROOT = path.join(import.meta.dir, "..", "..", "skills")
const DOCS_ROOT = path.join(import.meta.dir, "..", "..", "docs", "skills")
const read = (skill: string, rel = "SKILL.md") =>
  fs.readFileSync(path.join(ROOT, skill, rel), "utf8")
const readDocs = (skill: string) => fs.readFileSync(path.join(DOCS_ROOT, `${skill}.md`), "utf8")

describe("remaining skill body extractions", () => {
  test("ce-test-xcode keeps completion and routing inline while references own procedure", () => {
    const body = read("ce-test-xcode")
    const setup = read("ce-test-xcode", "references/setup-and-build.md")
    const run = read("ce-test-xcode", "references/test-and-report.md")
    const docs = readDocs("ce-test-xcode")

    expect(body).toMatch(/^description: "Test .* Use when /m)
    expect(body).toContain("**Done:**")
    expect(body).toContain("references/setup-and-build.md")
    expect(body).toContain("references/test-and-report.md")
    expect(body).not.toContain("mcp__xcodebuildmcp__")
    expect(run).toContain("xcrun simctl openurl")
    expect(setup).toContain("An empty argument or `current`")
    expect(run).toContain("An unanswered check is `SKIP`")
    expect(run).toContain("Only an applied fix triggers rebuild and retest")
    expect(setup).toContain("Testing does not authorize installing or configuring it")
    expect(body).toMatch(/status is derived from evidence, not the user's routing choice/i)
    expect(body).toMatch(/`FAIL` records observed failing evidence until a completed retest replaces it/i)
    expect(body).toMatch(/`SKIP` means the check has no completed outcome/i)
    const failureRoute = run.slice(run.indexOf("## Failure route"), run.indexOf("## Cleanup and summary"))
    expect(failureRoute).toMatch(/routing choice does not change the observed `FAIL`/i)
    expect(failureRoute).toMatch(/replacement status from the completed retest evidence/i)
    expect(failureRoute).toMatch(/until that evidence exists, retain `FAIL`/i)
    expect(failureRoute).toMatch(/Continue without investigation.*retain `FAIL`/is)
    expect(failureRoute).not.toMatch(/mark it `SKIP`/i)
    expect(run).toMatch(/any residual `FAIL` makes the result `FAIL`/i)
    expect(run).toMatch(/otherwise any `SKIP` makes it `PARTIAL`/i)
    expect(docs).toMatch(/choice does not change the observed Fail/i)
    expect(docs).toMatch(/Without completed retest evidence, preserve Fail/i)
    expect(docs).toMatch(/Skip is only for a check with no completed outcome/i)
    expect(docs).toMatch(/asks whether to investigate now or continue/i)
    expect(docs).not.toMatch(/asks fix-now or skip/i)
  })

  test("ce-polish loads startup mechanics and routes local commit ownership", () => {
    const body = read("ce-polish")
    const run = read("ce-polish", "references/run.md")
    const detection = read("ce-polish", "references/dev-server-detection.md")
    const rails = read("ce-polish", "references/dev-server-rails.md")
    const launchSchema = read("ce-polish", "references/launch-json-schema.md")
    const docs = readDocs("ce-polish")
    const recipes = ["rails", "next", "vite", "nuxt", "astro", "remix", "sveltekit", "procfile"].map(
      (type) => read("ce-polish", `references/dev-server-${type}.md`),
    )

    expect(body).toMatch(/^description: "Polish .* Use when /m)
    expect(body).toContain("**Done:**")
    expect(body).toContain("references/run.md")
    expect(body).toContain("invoke `ce-commit`")
    expect(body).not.toContain("agent-browser")
    expect(run).toContain("scripts/read-launch-json.sh")
    expect(run).toContain("scripts/resolve-port.sh")
    expect(run).toMatch(/when all four facts are usable, the tuple is complete: skip classification, recipe loading, package-manager resolution, and port resolution/i)
    expect(run).toMatch(/run project classification only when an unresolved command or port requires a project type/i)
    expect(run).toMatch(/read `references\/dev-server-<base-type>\.md` only when the command remains unresolved/i)
    expect(run).toMatch(/package-manager executable to complete the command/i)
    expect(run).toMatch(/run the port resolver only while the port remains unresolved/i)
    expect(run).toMatch(/without replacing a selected command, working directory, or environment/i)
    expect(run).toMatch(/ambiguous declarations remain in disambiguation/i)
    expect(run).toMatch(/for `unknown`, ask only for the unresolved tuple facts and do not guess/i)
    expect(run).toMatch(/operationally or leaves its required fact unknown, report that blocker/i)
    expect(run).toMatch(/offer once to save the completed tuple as `.claude\/launch.json`/i)
    expect(detection).toMatch(/runs only while the startup tuple's port remains unresolved/i)
    expect(detection).toMatch(/never replaces a selected command, working directory, or environment/i)
    for (const recipe of recipes) {
      expect(recipe).toMatch(/startup tuple still lacks a command/i)
    }
    expect(launchSchema).toMatch(/numeric value completes the tuple's port fact/i)
    expect(launchSchema).toMatch(/preserve facts from a selected configuration and add only what was resolved/i)
    expect(docs).toMatch(/configuration that supplies a usable tuple goes straight to startup/i)
    expect(docs).toMatch(/when a fact is missing, only the mechanism that can supply it runs/i)
    expect(docs).toMatch(/classification and the port resolver supply a missing port/i)
    const handoff = run.slice(run.indexOf("## Start and hand off"))
    expect(handoff).toMatch(/select exactly one intended server instance/i)
    expect(handoff).toMatch(/only when no intended instance is selected may .* be launched/i)
    expect(handoff).toMatch(/resolve the selected instance's actual URL/i)
    expect(handoff).toMatch(/http:\/\/localhost:<port>.*default candidate/i)
    expect(handoff).toMatch(/server output or a user correction replaces that candidate/i)
    expect(handoff).toMatch(/attribute successful reachability .* resolved actual URL .* selected instance/i)
    expect(handoff).toMatch(/browser-opening capability .* verified actual URL/i)
    expect(handoff).toContain("Dev server running on <verified-actual-url>")
    expect(handoff).toMatch(/last 20 log lines only when this run launched it/i)
    expect(handoff).toMatch(/correct the server URL or start configuration, or stop/i)
    expect(handoff).toMatch(/do not continue into the polish loop unless reachability is attributed/i)
    expect(rails).toMatch(/https:\/\/.*replaces the default HTTP candidate/i)
    expect(launchSchema).toMatch(/\| `port` \| no \|/)
    expect(launchSchema).toMatch(/schema does not lock the URL scheme/i)
    expect(docs).toMatch(/default `http:\/\/localhost:<port>` candidate/i)
    expect(docs).toMatch(/server output or your correction can identify a different actual URL/i)
    expect(docs).toMatch(/verified actual URL/i)
    expect(run).toContain("active harness")
  })

  test("Riffrec uses one portable analyzer invocation for both analysis paths", () => {
    const body = read("ce-riffrec-feedback-analysis")
    const analyzer = read("ce-riffrec-feedback-analysis", "references/analyzer.md")
    const quick = read("ce-riffrec-feedback-analysis", "references/quick-bug-report.md")
    const extensive = read("ce-riffrec-feedback-analysis", "references/extensive-analysis.md")

    expect(body).toMatch(/^description: "Analyze .* Use when .* Use for /m)
    expect(body).not.toMatch(/^description: .*\.(?:mp4|mov|webm|m4a|mp3|wav)/m)
    expect(body).toContain("**Done:**")
    expect(body).toContain("references/analyzer.md")
    expect(body).toContain("unless the user explicitly asked only to extract or analyze artifacts")
    expect(analyzer).toContain("for c in python3 python py")
    expect(analyzer).toContain('"$PY" "$SKILL_DIR/scripts/analyze_riffrec_zip.py"')
    expect(analyzer).toContain('OUTPUT_DIR="${OUTPUT_DIR:-}"')
    expect(analyzer).toContain('[ -z "$OUTPUT_DIR" ]')
    expect(analyzer).not.toContain("<input>")
    expect(quick).not.toMatch(/\bpython3?\b/)
    expect(extensive).toContain("leave it empty so the analyzer owns its default")
    expect(extensive).not.toMatch(/\bpython3?\b/)
  })
})
