#!/usr/bin/env bash

set -e

GIT_DIR=$(jj git root)
export GIT_DIR

if [ $# -eq 0 ]; then
    echo "Usage: resolve-pr-thread THREAD_ID"
    exit 1
fi

THREAD_ID=$1

GIT_DIR="$(jj git root)" gh api graphql -f threadId="$THREAD_ID" -f query='
mutation ResolveReviewThread($threadId: ID!) {
  resolveReviewThread(input: {threadId: $threadId}) {
    thread {
      id
      isResolved
      path
      line
    }
  }
}'
